### ISSUE TITLE
Cannot generate the example image

### ISSUE THREAD

**Issue by arielgoes** [noise-lab/NetDiffusion_Generator#2]
How can I generate the netflix_05.png?

![image](https://github.com/noise-lab/NetDiffusion_Generator/assets/35307478/23c9f872-42b2-4f66-a4dd-2281ab1680bf)

I've been trying distinct parameter configurations. However, it is not clear what ControlNet (w/ Canny) + Generation configurations you used.

Also is it expected the error: `Lora not found: test_task_model`?

I have ControlNet extension installed and identified.

I fed ControlNet with [nextflix_01.png](https://github.com/noise-lab/NetDiffusion_Generator/blob/main/data/preprocessed_fine_tune_imgs/netflix_01.png)

**Comment by arielgoes** [comment]
I managed to solve th e`Lora not found: test_task_model`error. However, the generated image stilll doesn't look like the one generated in the example you provided (i.e., [netflix_5.png](https://github.com/noise-lab/NetDiffusion_Generator/blob/b4335e52d88efa270823b3387b322005cd66771e/data/generated_imgs/netflix_5.png)).

**Comment by Bozolzr** [comment]
Can you tell me how you did that? Mine seems weird as well
![1711983933057](https://github.com/noise-lab/NetDiffusion_Generator/assets/105590685/ad1cb6c4-a916-4487-a2bc-9c0f313fc461)

**Comment by Bozolzr** [comment]
Did I make any mistakes in finetuning? I should have followed the instruction strictly

**Comment by TracyTd** [comment]
like this![image (2)](https://github.com/noise-lab/NetDiffusion_Generator/assets/128600241/78ba73fa-471d-4616-bda9-0f06642173ce)
